---
# tasks file for prometheus
#
- name: Create Prometheus service file
  become: true
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: restart prometheus

- name: Reload systemd to recognize Prometheus service
  become: true
  systemd:
    daemon_reload: yes

- name: Create Prometheus Group
  become: true
  group:
    name: "{{ prometheus_group }}"
    state: present

- name: Create Prometheus User
  become: true
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    system: true
    create_home: false

- name: Create Prometheus user and group
  become: true
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    system: true
    create_home: false

- name: Download Prometheus binaries
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

- name: Extract Prometheus tarball
  become: true
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/usr/local/src"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  loop:
    - "{{ prometheus_home }}"
    - "{{ prometheus_home }}/rules"
    - "{{ prometheus_home }}/data"

- name: Deploy configuration file
  become: true
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_home }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  notify: restart prometheus

- name: Copy prometheus binary
  become: true
  copy:
    src: "/usr/local/src/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Copy promtool binary
  become: true
  copy:
    src: "/usr/local/src/promtool"
    dest: "/usr/local/bin/promtool"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Ensure Prometheus is running
  become: true
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes
    service: prometheus.service
  notify: restart prometheus

